apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
        - name: gitops-demo-app
          image: IMAGE_PLACEHOLDER