apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: pasiol/gitops-demo-app
  newTag: d5a2977b1ee1665189949e8f5c35c335994f8028
